// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SameApi.Db.DbContexts;

#nullable disable

namespace SameApi.Db.Migrations
{
    [DbContext(typeof(SameApiDbContext))]
    [Migration("20250928204928_1.0.0")]
    partial class _100
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SameApi.Model.LKP.LKP_GenderDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LKP_SameApi_Gender");
                });

            modelBuilder.Entity("SameApi.Model.LKP.LKP_Profession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LKP_SameApi_Profession");
                });

            modelBuilder.Entity("SameApi.Model.LKP.LKP_School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProfession")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionId");

                    b.ToTable("LKP_SameApi_School");
                });

            modelBuilder.Entity("SameApi.Model.PostDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("SameApi_Post");
                });

            modelBuilder.Entity("SameApi.Model.UserDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GenderDaoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<int>("Number_follow")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostDaoId")
                        .HasColumnType("int");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolDaoId")
                        .HasColumnType("int");

                    b.Property<int>("id_gender_fk")
                        .HasColumnType("int");

                    b.Property<int>("id_post_fk")
                        .HasColumnType("int");

                    b.Property<int>("id_school_fk")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenderDaoId");

                    b.HasIndex("PostDaoId");

                    b.HasIndex("SchoolDaoId");

                    b.ToTable("SameApi_User");
                });

            modelBuilder.Entity("SameApi.Model.LKP.LKP_School", b =>
                {
                    b.HasOne("SameApi.Model.LKP.LKP_Profession", "Profession")
                        .WithMany()
                        .HasForeignKey("ProfessionId");

                    b.Navigation("Profession");
                });

            modelBuilder.Entity("SameApi.Model.UserDao", b =>
                {
                    b.HasOne("SameApi.Model.LKP.LKP_GenderDao", "GenderDao")
                        .WithMany()
                        .HasForeignKey("GenderDaoId");

                    b.HasOne("SameApi.Model.PostDao", "PostDao")
                        .WithMany()
                        .HasForeignKey("PostDaoId");

                    b.HasOne("SameApi.Model.LKP.LKP_School", "SchoolDao")
                        .WithMany()
                        .HasForeignKey("SchoolDaoId");

                    b.Navigation("GenderDao");

                    b.Navigation("PostDao");

                    b.Navigation("SchoolDao");
                });
#pragma warning restore 612, 618
        }
    }
}
